apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata: 
  name: xawsvms.xrds.skycluster.io
spec:
  group: xrds.skycluster.io
  names:
    kind: XAWSVM
    plural: xawsvms
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              forProvider:
                type: object
                properties:
                  flavorName:
                    type: string
                  imageName:
                    type: string
                  cloudInit:
                    type: string
                  sshKey:
                    type: string
              provider:
                type: object
                properties:
                  name:
                    type: string
                  region:
                    type: string
                  zone:
                    type: string
          status:
            type: object
            properties:
              atProvider:
                type: object
                properties:
                  network:
                    type: object
                    properties:
                      privateIpAddress:
                        type: string
                      publicIpAddress:
                        type: string