apiVersion: v1
entries:
  skycluster-dep:
  - apiVersion: v2
    appVersion: 0.1.1
    created: "2025-11-26T08:09:57.689084794Z"
    description: SkyCluster Dependency Helm Chart
    digest: 306be790a868b9b90af1305e0fcf6c039e94ae5b58a211a67f102e77b9111c7f
    name: skycluster-dep
    type: application
    urls:
    - https://skycluster.io/charts/skycluster-dep-0.1.4.tgz
    version: 0.1.4
  skycluster-main:
  - apiVersion: v2
    appVersion: 0.1.1
    created: "2025-11-26T08:09:57.695341524Z"
    description: SkyCluster Main Helm Chart
    digest: 63846f7a1517f5b68168060ea76bbe22e30307e95e4c51c61a5f29e1fe1ac74d
    name: skycluster-main
    type: application
    urls:
    - https://skycluster.io/charts/skycluster-main-0.1.4.tgz
    version: 0.1.4
generated: "2025-11-26T08:09:57.688132733Z"
